base.yml: fix IMAGE_INSTALL append spacing
Add leading whitespace to IMAGE_INSTALL:append to prevent package name
concatenation, which caused DNF "Unable to find a match" during rootfs.

Error: Unable to find a match: gst-plugins-imsdk-oss-metapackagegroup-audioreach

Signed-off-by: qti-sbojja <sbojja@qti.qualcomm.com>